# Local values (Kind)
postgres:
  storageClass: "standard" # standard on kind/docker desktop
  resources:
    requests:
      memory: "128Mi"
backend:
  resources:
    requests:
      memory: "256Mi"
storefront:
  resources:
    requests:
      memory: "128Mi"
redis:
  resources:
    requests:
      memory: "64Mi"
ingress:
  className: "nginx"
