apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: {{ .Values.storeName }}
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: {{ .Values.postgres.image }}
        env:
        - name: POSTGRES_USER
          value: {{ .Values.postgres.user }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgres.password }}
        - name: POSTGRES_DB
          value: {{ .Values.postgres.database }}
        ports:
        - containerPort: 5432
        resources:
          requests:
            memory: {{ .Values.postgres.resources.requests.memory }}
            cpu: {{ .Values.postgres.resources.requests.cpu }}
          limits:
            memory: {{ .Values.postgres.resources.limits.memory }}
            cpu: {{ .Values.postgres.resources.limits.cpu }}
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.postgres.storageClass }}
      resources:
        requests:
          storage: {{ .Values.postgres.storage }}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Values.storeName }}
spec:
  ports:
  - port: 5432
  selector:
    app: postgres
