# Local values (Kind/Minikube)
storeName: "local-store"
mysql:
  storageClass: "standard" # Usually standard on kind
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
wordpress:
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
ingress:
  className: "nginx"
  tls:
    enabled: false
