apiVersion: v1
kind: ServiceAccount
metadata:
  name: store-orchestrator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: store-orchestrator-role
rules:
- apiGroups: [""]
  resources: ["namespaces", "secrets", "services", "persistentvolumeclaims", "pods"]
  verbs: ["create", "delete", "get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["create", "delete", "get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["create", "delete", "get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "delete", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: store-orchestrator-binding
subjects:
- kind: ServiceAccount
  name: store-orchestrator
  namespace: default
roleRef:
  kind: ClusterRole
  name: store-orchestrator-role
  apiGroup: rbac.authorization.k8s.io
